### ISSUE TITLE
Unknown flag: --name

### ISSUE THREAD

**Issue by hervelemeur** [dailymotion/jx-pipelines-visualizer#2]
When executing the second command of the README, I've got an error:

```
➜ helm install jx-pipelines-visualizer/jx-pipelines-visualizer \
 --name jx-pipelines-visualizer \
 --namespace jx
Error: unknown flag: --name
```

I had to use this command instead to install the visualizer:

```
➜ helm install jx-pipelines-visualizer/jx-pipelines-visualizer \
 --generate-name=true \
 --namespace jx
```

Not sure what's wrong, here is the helm version I'm using:

```
helm version
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"dirty", GoVersion:"go1.15"}
```

**Comment by vbehar** [comment]
yes good catch, it's the syntax for Helm v2. For Helm v3, it's either `helm install RELEASE_NAME REPO/CHART`, or using the `generate-name` flag to automatically generate a name.

I'll fix the README
