### ISSUE TITLE
visualise the steps in the PipelineActivity

### ISSUE THREAD

**Issue by jstrachan** [dailymotion/jx-pipelines-visualizer#4]
it was mentioned on the last office hours that folks might add the ability to visualise the steps of pipelines.

I thought I’d mention this OSS CSS / icon and JS library that octant uses - clarity - it as a kind of pipeline visualisation widget 
https://clarity.design/documentation/timeline

which might be handy for rendering the pipeline steps?

**Comment by vbehar** [comment]
nice, thanks!
ping @florianorpeliere ;-)
