### ISSUE TITLE
PANIC: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by luca-poddigue** [dailymotion/jx-pipelines-visualizer#7]
Installed on Kubernetes v1.16.2

jx version
Version        2.1.149
Commit         a5c2cb9
Build date     2020-09-21T11:50:59Z
Go version     1.13.8
Git tree state clean

Stack trace when I try to open logs for a pipeline run:

`PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 2172 [running]:
github.com/urfave/negroni/v2.(*Recovery).ServeHTTP.func1(0x7fbc56c33a60, 0xc000b2e7f8, 0xc000ddcf00, 0xc000de0f50)
	/home/runner/work/jx-pipelines-visualizer/jx-pipelines-visualizer/vendor/github.com/urfave/negroni/v2/recovery.go:168 +0x166
panic(0x261f9a0, 0x409a390)
	/opt/hostedtoolcache/go/1.15.2/x64/src/runtime/panic.go:969 +0x175
github.com/jenkins-x/jx/v2/pkg/cloud/buckets.ReadHTTPURL(0xc00068e420, 0xa1, 0x0, 0x6fc23ac00, 0x0, 0x1e00, 0xc000dd5da0, 0x10)
	/home/runner/work/jx-pipelines-visualizer/jx-pipelines-visualizer/vendor/github.com/jenkins-x/jx/v2/pkg/cloud/buckets/buckets.go:79 +0xfa
github.com/jenkins-x/jx/v2/pkg/cloud/buckets.ReadURL(0xc00068e420, 0xa1, 0x6fc23ac00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/runner/work/jx-pipelines-visualizer/jx-pipelines-visualizer/vendor/github.com/jenkins-x/jx/v2/pkg/cloud/buckets/buckets.go:65 +0xb4
github.com/dailymotion/jx-pipelines-visualizer/web/handlers.(*LogsHandler).ServeHTTP(0xc000dcb8e0, 0x7fbc56c33a60, 0xc000b2e7f8, 0xc000ddd100)
	/home/runner/work/jx-pipelines-visualizer/jx-pipelines-visualizer/web/handlers/logs.go:58 +0x398
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000d15ec0, 0x7fbc56c33a60, 0xc000b2e7f8, 0xc000ddcf00)
	/home/runner/work/jx-pipelines-visualizer/jx-pipelines-visualizer/vendor/github.com/gorilla/mux/mux.go:210 +0xd3
github.com/urfave/negroni/v2.Wrap.func1(0x7fbc56c33a60, 0xc000b2e7f8, 0xc000ddcf00, 0xc000dcbf60)
	/home/runner/work/jx-pipelines-visualizer/jx-pipelines-visualizer/vendor/github.com/urfave/negroni/v2/negroni.go:55 +0x4d
github.com/urfave/negroni/v2.HandlerFunc.ServeHTTP(0xc000dcbf20, 0x7fbc56c33a60, 0xc000b2e7f8, 0xc000ddcf00, 0xc000dcbf60)
	/home/runner/work/jx-pipelines-visualizer/jx-pipelines-visualizer/vendor/github.com/urfave/negroni/v2/negroni.go:29 +0x4e
github.com/urfave/negroni/v2.middleware.ServeHTTP(...)
	/home/runner/work/jx-pipelines-visualizer/jx-pipelines-visualizer/vendor/github.com/urfave/negroni/v2/negroni.go:47
github.com/urfave/negroni/v2.(*Static).ServeHTTP(0xc000dfc450, 0x7fbc56c33a60, 0xc000b2e7f8, 0xc000ddcf00, 0xc000dcbf80)
	/home/runner/work/jx-pipelines-visualizer/jx-pipelines-visualizer/vendor/github.com/urfave/negroni/v2/static.go:41 +0xf9
github.com/urfave/negroni/v2.middleware.ServeHTTP(...)
	/home/runner/work/jx-pipelines-visualizer/jx-pipelines-visualizer/vendor/github.com/urfave/negroni/v2/negroni.go:47
github.com/urfave/negroni/v2.(*Recovery).ServeHTTP(0xc000de0f50, 0x7fbc56c33a60, 0xc000b2e7f8, 0xc000ddcf00, 0xc000dcbfa0)
	/home/runner/work/jx-pipelines-visualizer/jx-pipelines-visualizer/vendor/github.com/urfave/negroni/v2/recovery.go:210 +0x8c
github.com/urfave/negroni/v2.middleware.ServeHTTP(...)
	/home/runner/work/jx-pipelines-visualizer/jx-pipelines-visualizer/vendor/github.com/urfave/negroni/v2/negroni.go:47
github.com/urfave/negroni/v2.(*Negroni).ServeHTTP(0xc000dfc4b0, 0x2e10560, 0xc000afe0e0, 0xc000ddcf00)
	/home/runner/work/jx-pipelines-visualizer/jx-pipelines-visualizer/vendor/github.com/urfave/negroni/v2/negroni.go:107 +0xfb
net/http.(*ServeMux).ServeHTTP(0x40cb7a0, 0x2e10560, 0xc000afe0e0, 0xc000ddcf00)
	/opt/hostedtoolcache/go/1.15.2/x64/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc000dea0e0, 0x2e10560, 0xc000afe0e0, 0xc000ddcf00)
	/opt/hostedtoolcache/go/1.15.2/x64/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc000df6780, 0x2e18820, 0xc000db3c00)
	/opt/hostedtoolcache/go/1.15.2/x64/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.15.2/x64/src/net/http/server.go:2969 +0x36c`

**Comment by vbehar** [comment]
thanks for the bug report. It seems you're not storing your logs in a GCS bucket. Can you please share where are stored your logs? the `storage.logs` section of your `jx-requirements.yml` file. thanks

**Comment by luca-poddigue** [comment]
Actually I'm not storing logs anywhere. I didn't realize it was a requirement.
I'm on on-prem Kubernetes. Would it be feasible to store them on a PVC instead of a remote storage bucket?

**Comment by vbehar** [comment]
it's not a requirement to store your logs, but if you don't do it, you won't be able to read logs from deleted containers. So it's highly recommended.

you can create an issue in the jx project to ask for the ability to store the logs in a PVC
